In [28]:
from sklearn import neighbors, datasets
from sklearn.neural_network import MLPClassifier
import numpy as np

#Carrega a base de dados
dados1 = datasets.load_breast_cancer()
#dados2 = datasets.load_boston()
#dados3 = datasets.load_iris()

#Cria um vetor aleatorio de mesma qtde de instancias da base de dados para criar conjuntos de treinamento aleatorio
perm1 = np.random.permutation(dados1.target.size)
#perm2 = np.random.permutation(dados2.target.size)
#perm3 = np.random.permutation(dados3.target.size)

#Cria dados para treinamento e testes escolhidos aleatoriamente
dados_cancer = dados1.data[perm1]
dados_cancer_rotulos = dados1.target[perm1] 
##
#dados_boston = dados2.data[perm2]
#dados_boston_rotulos = dados2.target[perm2]
##
#dados_iris = dados3.data[perm3]
#dados_iris_rotulos = dados3.target[perm3]
##

dados_cancer_treina = dados_cancer[:len(dados_cancer)//2]
dados_cancer_treina_rotulos = dados_cancer_rotulos[:len(dados_cancer_rotulos)//2]
##
#dados_boston_treina = dados_boston[:len(dados_boston)//2]
#dados_boston_treina_rotulos = dados_boston_rotulos[:len(dados_boston_rotulos)//2]
##
#dados_iris_treina = dados_iris[:len(dados_iris)//2]
#dados_iris_treina_rotulos = dados_iris_rotulos[:len(dados_iris_rotulos)//2]

dados_cancer_teste = dados_cancer[len(dados_cancer)//2:]
dados_cancer_teste_rotulos = dados_cancer_rotulos[len(dados_cancer_rotulos)//2:]
##
#dados_boston_teste = dados_boston[len(dados_boston)//2:]
#dados_boston_teste_rotulos = dados_boston_rotulos[len(dados_boston_rotulos)//2:]
##
#dados_iris_teste = dados_iris[len(dados_iris)//2:]
#dados_iris_teste_rotulos = dados_iris_rotulos[len(dados_iris_rotulos)//2:]


#Algoritmo KNN e MLP
knn = neighbors.KNeighborsClassifier()
mlp = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(100,),random_state=3)

#Treinamento
knn.fit(dados_cancer_treina, dados_cancer_treina_rotulos)
#knn.fit(dados_boston_treina, dados_boston_treina_rotulos)
#knn.fit(dados_iris_treina, dados_iris_treina_rotulos)

mlp.fit(dados_cancer_treina, dados_cancer_treina_rotulos)
#mlp.fit(dados_boston_treina, dados_boston_treina_rotulos)
#mlp.fit(dados_iris_treina, dados_iris_treina_rotulos)

#Avaliacao

print (knn.score(dados_cancer_teste, dados_cancer_teste_rotulos))
#print (knn.score(dados_boston_teste, dados_boston_teste_rotulos))
#print (knn.score(dados_iris_teste, dados_iris_teste_rotulos))

print (mlp.score(dados_cancer_teste, dados_cancer_teste_rotulos))
#print (mlp.score(dados_boston_teste, dados_boston_teste_rotulos))
#print (mlp.score(dados_iris_teste, dados_iris_teste_rotulos))


0.922807017544
0.936842105263


In [61]:
from sklearn import neighbors, datasets
from sklearn.neural_network import MLPClassifier
import numpy as np

#Carrega a base de dados
#dados1 = datasets.load_breast_cancer()
dados2 = datasets.load_digits()
#dados3 = datasets.load_iris()

#Cria um vetor aleatorio de mesma qtde de instancias da base de dados para criar conjuntos de treinamento aleatorio
#perm1 = np.random.permutation(dados1.target.size)
perm2 = np.random.permutation(dados2.target.size)
#perm3 = np.random.permutation(dados3.target.size)

#Cria dados para treinamento e testes escolhidos aleatoriamente
#dados_cancer = dados1.data[perm1]
#dados_cancer_rotulos = dados1.target[perm1] 
##
dados_boston = dados2.data[perm2]
dados_boston_rotulos = dados2.target[perm2]
##
#dados_iris = dados3.data[perm3]
#dados_iris_rotulos = dados3.target[perm3]
##

#dados_cancer_treina = dados_cancer[:len(dados_cancer)//2]
#dados_cancer_treina_rotulos = dados_cancer_rotulos[:len(dados_cancer_rotulos)//2]
##
dados_boston_treina = dados_boston[:len(dados_boston)//2]
dados_boston_treina_rotulos = dados_boston_rotulos[:len(dados_boston_rotulos)//2]
##
#dados_iris_treina = dados_iris[:len(dados_iris)//2]
#dados_iris_treina_rotulos = dados_iris_rotulos[:len(dados_iris_rotulos)//2]

#dados_cancer_teste = dados_cancer[len(dados_cancer)//2:]
#dados_cancer_teste_rotulos = dados_cancer_rotulos[len(dados_cancer_rotulos)//2:]
##
dados_boston_teste = dados_boston[len(dados_boston)//2:]
dados_boston_teste_rotulos = dados_boston_rotulos[len(dados_boston_rotulos)//2:]
##
#dados_iris_teste = dados_iris[len(dados_iris)//2:]
#dados_iris_teste_rotulos = dados_iris_rotulos[len(dados_iris_rotulos)//2:]


#Algoritmo KNN e MLP
knn = neighbors.KNeighborsClassifier()
mlp = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(100,),random_state=3)

#Treinamento
#knn.fit(dados_cancer_treina, dados_cancer_treina_rotulos)
knn.fit(dados_boston_treina, dados_boston_treina_rotulos)
#knn.fit(dados_iris_treina, dados_iris_treina_rotulos)

#mlp.fit(dados_cancer_treina, dados_cancer_treina_rotulos)
mlp.fit(dados_boston_treina, dados_boston_treina_rotulos)
#mlp.fit(dados_iris_treina, dados_iris_treina_rotulos)

#Avaliacao

#print (knn.score(dados_cancer_teste, dados_cancer_teste_rotulos))
print (knn.score(dados_boston_teste, dados_boston_teste_rotulos))
#print (knn.score(dados_iris_teste, dados_iris_teste_rotulos))

#print (mlp.score(dados_cancer_teste, dados_cancer_teste_rotulos))
print (mlp.score(dados_boston_teste, dados_boston_teste_rotulos))
#print (mlp.score(dados_iris_teste, dados_iris_teste_rotulos))


0.983314794216
0.967741935484


In [30]:
from sklearn import neighbors, datasets
from sklearn.neural_network import MLPClassifier
import numpy as np

#Carrega a base de dados
#dados1 = datasets.load_breast_cancer()
#dados2 = datasets.load_boston()
dados3 = datasets.load_iris()

#Cria um vetor aleatorio de mesma qtde de instancias da base de dados para criar conjuntos de treinamento aleatorio
#perm1 = np.random.permutation(dados1.target.size)
#perm2 = np.random.permutation(dados2.target.size)
perm3 = np.random.permutation(dados3.target.size)

#Cria dados para treinamento e testes escolhidos aleatoriamente
#dados_cancer = dados1.data[perm1]
#dados_cancer_rotulos = dados1.target[perm1] 
##
#dados_boston = dados2.data[perm2]
#dados_boston_rotulos = dados2.target[perm2]
##
dados_iris = dados3.data[perm3]
dados_iris_rotulos = dados3.target[perm3]
##

#dados_cancer_treina = dados_cancer[:len(dados_cancer)//2]
#dados_cancer_treina_rotulos = dados_cancer_rotulos[:len(dados_cancer_rotulos)//2]
##
#dados_boston_treina = dados_boston[:len(dados_boston)//2]
#dados_boston_treina_rotulos = dados_boston_rotulos[:len(dados_boston_rotulos)//2]
##
dados_iris_treina = dados_iris[:len(dados_iris)//2]
dados_iris_treina_rotulos = dados_iris_rotulos[:len(dados_iris_rotulos)//2]

#dados_cancer_teste = dados_cancer[len(dados_cancer)//2:]
#dados_cancer_teste_rotulos = dados_cancer_rotulos[len(dados_cancer_rotulos)//2:]
##
#dados_boston_teste = dados_boston[len(dados_boston)//2:]
#dados_boston_teste_rotulos = dados_boston_rotulos[len(dados_boston_rotulos)//2:]
##
dados_iris_teste = dados_iris[len(dados_iris)//2:]
dados_iris_teste_rotulos = dados_iris_rotulos[len(dados_iris_rotulos)//2:]


#Algoritmo KNN e MLP
knn = neighbors.KNeighborsClassifier()
mlp = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(100,),random_state=3)

#Treinamento
#knn.fit(dados_cancer_treina, dados_cancer_treina_rotulos)
#knn.fit(dados_boston_treina, dados_boston_treina_rotulos)
knn.fit(dados_iris_treina, dados_iris_treina_rotulos)

#mlp.fit(dados_cancer_treina, dados_cancer_treina_rotulos)
#mlp.fit(dados_boston_treina, dados_boston_treina_rotulos)
mlp.fit(dados_iris_treina, dados_iris_treina_rotulos)

#Avaliacao

#print (knn.score(dados_cancer_teste, dados_cancer_teste_rotulos))
#print (knn.score(dados_boston_teste, dados_boston_teste_rotulos))
print (knn.score(dados_iris_teste, dados_iris_teste_rotulos))

#print (mlp.score(dados_cancer_teste, dados_cancer_teste_rotulos))
#print (mlp.score(dados_boston_teste, dados_boston_teste_rotulos))
print (mlp.score(dados_iris_teste, dados_iris_teste_rotulos))


0.946666666667
0.973333333333


In [115]:
from sklearn import neighbors, datasets
from sklearn.neural_network import MLPClassifier
import numpy as np

#Carrega a base de dados
dados1 = datasets.load_breast_cancer()
dados2 = datasets.load_digits()
dados3 = datasets.load_iris()

#Cria um vetor aleatorio de mesma qtde de instancias da base de dados para criar conjuntos de treinamento aleatorio
perm1 = np.random.permutation(dados1.target.size)
perm2 = np.random.permutation(dados2.target.size)
perm3 = np.random.permutation(dados3.target.size)

#Cria dados para treinamento e testes escolhidos aleatoriamente
dados_cancer = dados1.data[perm1]
dados_cancer_rotulos = dados1.target[perm1] 
##
dados_digits = dados2.data[perm2]
dados_digits_rotulos = dados2.target[perm2]
##
dados_iris = dados3.data[perm3]
dados_iris_rotulos = dados3.target[perm3]
##

dados_cancer_treina = dados_cancer[:len(dados_cancer)//2]
dados_cancer_treina_rotulos = dados_cancer_rotulos[:len(dados_cancer_rotulos)//2]
##
dados_digits_treina = dados_digits[:len(dados_digits)//2]
dados_digits_treina_rotulos = dados_digits_rotulos[:len(dados_digits_rotulos)//2]
##
dados_iris_treina = dados_iris[:len(dados_iris)//2]
dados_iris_treina_rotulos = dados_iris_rotulos[:len(dados_iris_rotulos)//2]

dados_cancer_teste = dados_cancer[len(dados_cancer)//2:]
dados_cancer_teste_rotulos = dados_cancer_rotulos[len(dados_cancer_rotulos)//2:]
##
dados_digits_teste = dados_digits[len(dados_digits)//2:]
dados_digits_teste_rotulos = dados_digits_rotulos[len(dados_digits_rotulos)//2:]
##
dados_iris_teste = dados_iris[len(dados_iris)//2:]
dados_iris_teste_rotulos = dados_iris_rotulos[len(dados_iris_rotulos)//2:]


#Algoritmo KNN e MLP
knn_cancer = neighbors.KNeighborsClassifier()
knn_digits = neighbors.KNeighborsClassifier()
knn_iris = neighbors.KNeighborsClassifier()
mlp_cancer = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(100,),random_state=3)
mlp_digits = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(100,),random_state=3)
mlp_iris = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(100,),random_state=3)

#Treinamento
knn_cancer.fit(dados_cancer_treina, dados_cancer_treina_rotulos)
knn_digits.fit(dados_digits_treina, dados_digits_treina_rotulos)
knn_iris.fit(dados_iris_treina, dados_iris_treina_rotulos)

mlp_cancer.fit(dados_cancer_treina, dados_cancer_treina_rotulos)
mlp_digits.fit(dados_digits_treina, dados_digits_treina_rotulos)
mlp_iris.fit(dados_iris_treina, dados_iris_treina_rotulos)

#Avaliacao

print ("Accuracy knn_cancer: ",knn_cancer.score(dados_cancer_teste, dados_cancer_teste_rotulos))
print ("Accuracy knn_digits: ",knn_digits.score(dados_digits_teste, dados_digits_teste_rotulos))
print ("Accuracy knn_iris: ",knn_iris.score(dados_iris_teste, dados_iris_teste_rotulos))

print ("Accuracy mlp_cancer: ",mlp_cancer.score(dados_cancer_teste, dados_cancer_teste_rotulos))
print ("Accuracy mlp_digits: ",mlp_digits.score(dados_digits_teste, dados_digits_teste_rotulos))
print ("Accuracy mlp_iris: ",mlp_iris.score(dados_iris_teste, dados_iris_teste_rotulos))


Accuracy knn_cancer:  0.922807017544
Accuracy knn_digits:  0.976640711902
Accuracy knn_iris:  0.96
Accuracy mlp_cancer:  0.922807017544
Accuracy mlp_digits:  0.955506117909
Accuracy mlp_iris:  0.973333333333


In [117]:
from sklearn import neighbors, datasets
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import numpy as np

#Carrega a base de dados
dados1 = datasets.load_breast_cancer()
dados2 = datasets.load_digits()
dados3 = datasets.load_iris()

#Cria dados para treinamento e testes escolhidos aleatoriamente
cancer_treina, cancer_teste, cancer_treina_rotulos, cancer_teste_rotulos = train_test_split(dados1.data,dados1.target,test_size=0.5)

#Algoritmo KNN e MLP
knn_cancer = neighbors.KNeighborsClassifier()

#Treinamento
knn_cancer.fit(cancer_treina, cancer_treina_rotulos)

#Avaliacao

print ("Accuracy knn_cancer: ",knn_cancer.score(cancer_teste, cancer_teste_rotulos))


Accuracy knn_cancer:  0.943859649123


In [ ]:
from sklearn import neighbors, datasets
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split, cross_val_score, ShuffleSplit
import numpy as np

#Carrega a base de dados
dados1 = datasets.load_breast_cancer()
dados2 = datasets.load_digits()
dados3 = datasets.load_iris()

#Partição
cv = ShuffleSplit (n_splits=5, test_size=0.4)

#Algoritmo KNN
knn_cancer = neighbors.KNeighborsClassifier()


In [40]:
from sklearn import neighbors, datasets
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split, cross_val_score, ShuffleSplit
import numpy as np

#Carrega a base de dados
dados1 = datasets.load_breast_cancer()
dados2 = datasets.load_digits()
dados3 = datasets.load_iris()

#Partição
cv = ShuffleSplit (n_splits=5, test_size=0.4)

#Algoritmo KNN
knn_cancer = neighbors.KNeighborsClassifier()
knn_digits = neighbors.KNeighborsClassifier()
knn_iris = neighbors.KNeighborsClassifier()

#Cross Validation KNN 
scores_knn_cancer = cross_val_score(knn_cancer, dados1.data, dados1.target, cv=cv)
scores_knn_digits = cross_val_score(knn_digits, dados2.data, dados2.target, cv=cv)
scores_knn_iris = cross_val_score(knn_iris, dados3.data, dados3.target, cv=cv)

#Algoritmo MLP
mlp_cancer = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(100,),random_state=3)
mlp_digits = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(100,),random_state=3)
mlp_iris = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(100,),random_state=3)

#Cross Validation MLP
scores_mlp_cancer = cross_val_score(mlp_cancer, dados1.data, dados1.target, cv=cv)
scores_mlp_digits = cross_val_score(mlp_digits, dados2.data, dados2.target, cv=cv)
scores_mlp_iris = cross_val_score(mlp_iris, dados3.data, dados3.target, cv=cv)

print (scores_knn_cancer)
print("Accuracy knn_cancer: %0.2f (+/- %0.2f)" % (scores_knn_cancer.mean(), scores_knn_cancer.std() * 2))

print (scores_knn_digits)
print("Accuracy knn_digits: %0.2f (+/- %0.2f)" % (scores_knn_digits.mean(), scores_knn_digits.std() * 2))

print (scores_knn_iris)
print("Accuracy knn_iris: %0.2f (+/- %0.2f)" % (scores_knn_iris.mean(), scores_knn_iris.std() * 2))

print (scores_mlp_cancer)
print ("Accuracy mlp_cancer: %0.2f (+/- %0.2f)" % (scores_mlp_cancer.mean(), scores_mlp_cancer.std() *2))

print (scores_mlp_digits)
print ("Accuracy mlp_digits: %0.2f (+/- %0.2f)" % (scores_mlp_digits.mean(), scores_mlp_digits.std() *2))

print (scores_mlp_iris)
print ("Accuracy mlp_iris: %0.2f (+/- %0.2f)" % (scores_mlp_iris.mean(), scores_mlp_iris.std() *2))


[ 0.96871624  0.959281    0.94295022  0.95804989  0.96535669]
Accuracy knn_cancer: 0.96 (+/- 0.02)
[ 0.97913769  0.98331015  0.98052851  0.97913769  0.97774687]
Accuracy knn_digits: 0.98 (+/- 0.00)
[ 0.95        0.95        0.96666667  0.95        0.96666667]
Accuracy knn_iris: 0.96 (+/- 0.02)
[ 0.96929825  0.95175439  0.92982456  0.92982456  0.93421053]
Accuracy mlp_cancer: 0.94 (+/- 0.03)
[ 0.96522949  0.96662031  0.96383866  0.96940195  0.95688456]
Accuracy mlp_digits: 0.96 (+/- 0.01)
[ 0.96666667  0.95        1.          0.93333333  0.95      ]
Accuracy mlp_iris: 0.96 (+/- 0.05)
